### ISSUE TITLE
pkgx bundler install fails

### ISSUE THREAD

**Issue by krzyzanowskim** [pkgxdev/pkgx#861] opened 2023-11-18 10:59 UTC
I realized I'm unable to use `bundler` package for some reason. I'm not sure what to do about it

❯ pkgx bundler install
There was an error while trying to write to `/usr/local/lib/ruby/gems/3.2.0`. It is likely that you need to grant a write
permissions for that path.

❯ which bundler
/Users/marcinkrzyzanowski/.local/bin/bundler

❯ pkgx install bundler
pkgx: already installed: bundle (rubygems.org)
pkgx: already installed: bundler (rubygems.org)
pkgx: already installed: gem (rubygems.org)

❯ pkgx --version
pkgx 1.1.0

It looks like gem points to that directory, but it shouldn't, should it?

❯ which gem
/Users/marcinkrzyzanowski/.local/bin/gem

❯ gem environment gemdir
/usr/local/lib/ruby/gems/3.2.0

- GEM PATHS:
     - /usr/local/lib/ruby/gems/3.2.0
     - /Users/marcinkrzyzanowski/.gem/ruby/3.2.0
     - /Users/marcinkrzyzanowski/.pkgx/ruby-lang.org/v3.2.2/lib/ruby/gems/3.2.0

**Comment by mxcl** [comment] 2023-11-18 12:04
Hey @krzyzanowskim long time no see.

So the bug is that the gem path should be a writable path? This is true for `gem` itself so clearly there's some misconfiguration that propogates into `bundler` that we need to fix.

> It looks like gem points to that directory, but it shouldn't, should it?

Sorry I can't figure out what you mean by this.

**Comment by krzyzanowskim** [comment] 2023-11-18 12:07
I'm not proficient, I just don't know what makes it point to `/usr/local/lib/ruby` that is not nonexistent. I guess that is comes from `INSTALLATION DIRECTORY`

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.22
  - RUBY VERSION: 3.2.2 (2023-03-30 patchlevel 53) [arm64-darwin22]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/3.2.0
  - USER INSTALLATION DIRECTORY: /Users/marcinkrzyzanowski/.gem/ruby/3.2.0
```

**Comment by wojtha** [comment] 2023-12-21 15:30
it seems that I found the root cause the pkgx ruby 3.2 install some weird version of the rubygems package:

`/Users/wojtha/.pkgx/rubygems.org/v3.4.22/lib/rubygems/defaults.rb`

This file contains the hardcoded method pointing to the system path:

```ruby
  def self.default_system_dir
    File.join("/usr/local/lib/ruby/gems", RbConfig::CONFIG["ruby_version"])
  end
```

I've compared the file with the version on github and this method is not present there 🤷🏻 I seems like some ad hoc hack at the pkgx side as I cannot find [this method in the original repository](https://github.com/rubygems/rubygems/blob/v3.4.22/lib/rubygems/defaults.rb).

When I updated the rubygems the method and issue went away...

```
env +ruby@3.2
gem update --system 3.5.1
```

**Comment by wojtha** [comment] 2023-12-21 15:58
Also when I upgrade rubygems to 3.5.1 via `gem update --system 3.5.1` it rewrites the files inside the `/Users/wojtha/.pkgx/rubygems.org/v3.4.22/`

**Comment by michaelessiet** [comment] 2024-01-04 17:56
We don't recommend using the package's update/upgrade command. Whenever you want to upgrade a pkgx package do something like this `pkgx gem@latest <command>`. But if you installed the package using the `pkgx install gem` command then you can use `gem update` since the package will be installed in the `.local/bin` dir

**Comment by mxcl** [comment] 2024-01-05 12:58
The issue was fixed in the pantry.

@wojtha this is what I would expect the command to do. What did you expect?

**Closed by mxcl** 2024-01-05 12:58 UTC

**Comment by wojtha** [comment] 2024-01-08 22:45
@mxcl I guess I understand that now too, but those were my first hours with `pkgx` and I found it confusing that `rubygems.org/v3.4.22` could be rewritten by a completely different version, sort of unintentionally. I also didn't know at that time there is a companion `pantry` project and what it does.
