### ISSUE TITLE
Running tea install again fails

### ISSUE THREAD

**Issue by dcvz** [pkgxdev/pkgx#753] opened 2023-09-28 09:25 UTC
If you run `tea install xxx` it will successfully install a package. If you run the command again it'll fail with:
```bash
× unexpected error file-exists:/Users/dcvz/.local/bin/libpng-config
│ Error: file-exists:/Users/dcvz/.local/bin/libpng-config
│     at Path.write (https://deno.land/x/libtea@v0.13.0/src/utils/Path.ts:337:25)
│     at write (file:///Users/builder/actions-runner/_work/cli/cli/src/modes/install.ts:20:11)
│     at eventLoopTick (ext:core/01_core.js:183:11)
│     at async default (file:///Users/builder/actions-runner/_work/cli/cli/src/modes/install.ts:11:5)
│     at async default (file:///Users/builder/actions-runner/_work/cli/cli/src/app.ts:84:7)
│     at async file:///Users/builder/actions-runner/_work/cli/cli/entrypoint.ts:68:3
╰─➤ https://github.com/teaxyz/cli/issues/new
```

Is the intended outcome? Should it not try to replace with the latest version? Also, I guess tea should know if tea itself was who installed it, so the error could likely be more helpful.

**Comment by mxcl** [comment] 2023-09-28 10:36
a bug yes, tho not too serious so probs will fix for 1.0.1

**Comment by kevinmichaelchen** [comment] 2023-09-29 23:19
dupe of #745 :)

**Comment by mxcl** [comment] 2023-10-02 20:08
Thanks Kevin, closing in favor of #745.

**Closed by mxcl** 2023-10-02 20:08 UTC
